<?php
/** Mobile-first, WhatsApp-focused renderer shared by all /lp/ program URLs. */
$GTM = 'GTM-MMZHD3HN'; $WA = '6287759151278'; $year = date('Y');
$e = fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
$imageUrl = fn($f) => '/lp/images/' . ltrim((string)$f, '/');
$program = $LP['program_name'] ?? 'Pelatihan K3'; $slug = $LP['slug'] ?? 'pelatihan-k3';
$LP_CONTENT = []; @include __DIR__ . '/_lp-content.php';
$LP = array_merge($LP_CONTENT[$slug] ?? [], $LP);
$heroCta = $LP['hero_cta'] ?? 'Cek Syarat & Kursi'; $stickyCta = $LP['sticky_cta'] ?? 'Cek Syarat via WhatsApp'; $priceCta = $LP['price_cta'] ?? 'Minta Rincian Biaya';
$heroImage = $LP['hero_image'] ?? 'pelatihan-030.webp'; $heroAlt = $LP['hero_alt'] ?? "Dokumentasi {$program}";
$price = $LP['promo_price'] ?? ($LP['price'] ?? 'Hubungi kami'); $oldPrice = !empty($LP['promo_price']) ? ($LP['price'] ?? '') : '';
$summary = $LP['summary'] ?? []; $schedule = '';
foreach ($summary as $row) if (in_array(strtolower(strip_tags((string)$row[0])), ['tanggal','jadwal'], true)) { $schedule = strip_tags((string)$row[1]); break; }
$gallery = $LP['gallery'] ?? [['pelatihan-030.webp','Briefing keselamatan di lingkungan industri'],['pelatihan-010.webp','Kelas bersama instruktur praktisi'],['pelatihan-050.webp','Praktik keselamatan secara langsung']];
$audience = $LP['audience'] ?? ['Profesional yang ingin meningkatkan kompetensi sesuai bidangnya','Peserta yang memenuhi persyaratan pendidikan atau pengalaman skema','Perusahaan yang membutuhkan pelatihan reguler atau in-house'];
$outcomes = $LP['outcomes'] ?? [['Pilih skema dengan tepat','Tim membantu mencocokkan tujuan, latar belakang, dan persyaratan sebelum Anda membayar.'],['Siap mengikuti proses','Dapatkan arahan materi, dokumen, jadwal, dan tahapan asesmen secara jelas.'],['Administrasi lebih ringan','Tim mendampingi kelengkapan administrasi dari pendaftaran sampai proses selesai.']];
$topics = $LP['topics'] ?? ['Dasar dan ruang lingkup program','Identifikasi bahaya atau kebutuhan teknis','Penerapan prosedur di lingkungan kerja','Persiapan evaluasi dan proses lanjutan'];
$requirements = $LP['requirements'] ?? ['Identitas diri dan pas foto','Ijazah pendidikan terakhir','CV atau riwayat pengalaman kerja','Dokumen tambahan mengikuti persyaratan skema'];
$includes = $LP['incl'] ?? ['Pelatihan dan materi pembelajaran','Proses asesmen sesuai program','Pendampingan administrasi','Informasi jadwal dan persyaratan','Instruktur berpengalaman','Dukungan sampai proses selesai'];
$faqs = $LP['faqs'] ?? [['Apakah saya memenuhi persyaratan?','Persyaratan bergantung pada pendidikan, pengalaman, dan skema yang dipilih. Kirim profil singkat melalui WhatsApp agar tim memeriksanya sebelum Anda mendaftar.'],['Apakah sertifikat pasti diterbitkan?','Penerbitan sertifikat kompetensi mengikuti hasil asesmen dan ketentuan lembaga penerbit. Tim akan menjelaskan tahapan dan dokumen yang diperlukan sebelum pendaftaran.'],['Apa saja yang termasuk dalam biaya?','Fasilitas dan komponen biaya akan dikonfirmasi secara tertulis sebelum pembayaran agar Anda dapat mengambil keputusan dengan jelas.'],['Apakah tersedia kelas online atau in-house?','Metode pelaksanaan berbeda untuk setiap program dan batch. Tim akan menginformasikan pilihan online, tatap muka Yogyakarta, atau in-house yang sedang tersedia.']];
$clientLogos = $LP['client_logos'] ?? [
  ['klien/78a55-pertamina.png','Pertamina'],['klien/58303-pln-persero.png','PLN'],
  ['klien/1bbc3-wika.png','WIKA'],['klien/5147b-waskita.png','Waskita'],
  ['klien/78168-pt-antam.png','ANTAM'],['klien/46e2f-petrokimia.png','Petrokimia'],
  ['klien/48046-kai.png','KAI'],['klien/83141-unilever.png','Unilever'],
  ['klien/b5c3d-telkomsel-logo-capi.png','Telkomsel'],['klien/8e764-ugm-clien.jpg','UGM'],
  ['klien/c306e-adaro.png','Adaro'],['klien/d23da-samsung-cnt.png','Samsung C&T'],
];
$waMessage = $LP['wa_msg'] ?? "Halo Wahana Totalita, saya ingin mengecek persyaratan {$program}. Mohon bantu informasikan jadwal dan biayanya.";
$waUrl = fn($intent) => 'https://wa.me/' . $WA . '?text=' . rawurlencode($waMessage . "\n\nKeperluan: {$intent}\nHalaman: {$slug}");
$WASVG = '<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M17.5 14.4c-.3-.1-1.8-.9-2-1-.3-.1-.5-.1-.7.1-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-.3-.2-1.3-.5-2.4-1.5-.9-.8-1.5-1.8-1.7-2-.2-.3 0-.5.1-.6l.5-.5c.1-.2.2-.3.3-.5.1-.2 0-.4 0-.5l-.9-2.2c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.1.2 2.1 3.2 5.1 4.5.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.8-.7 2-1.4.2-.7.2-1.3.2-1.4-.1-.1-.3-.2-.6-.3M12 2a10 10 0 0 0-8.6 15l-1.3 4.7 4.8-1.3A10 10 0 1 0 12 2z"/></svg>';
$courseSchema = ['@context'=>'https://schema.org','@type'=>'Course','name'=>strip_tags($program),'description'=>$LP['meta_desc'] ?? $LP['lead'] ?? '','provider'=>['@type'=>'Organization','name'=>'Wahana Totalita Konsultan','url'=>'https://wahanatotalita.com/']];
$faqSchema = ['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>array_map(fn($f)=>['@type'=>'Question','name'=>$f[0],'acceptedAnswer'=>['@type'=>'Answer','text'=>$f[1]]],$faqs)];
?><!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= $e($LP['title'] ?? $program) ?></title><meta name="description" content="<?= $e($LP['meta_desc'] ?? $LP['lead'] ?? '') ?>"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="https://wahanatotalita.com/lp/<?= $e($slug) ?>">
<meta property="og:type" content="website"><meta property="og:title" content="<?= $e($LP['title'] ?? $program) ?>"><meta property="og:description" content="<?= $e($LP['meta_desc'] ?? $LP['lead'] ?? '') ?>"><meta property="og:image" content="https://wahanatotalita.com<?= $e($imageUrl($heroImage)) ?>"><link rel="preload" as="image" href="<?= $e($imageUrl($heroImage)) ?>" fetchpriority="high"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&amp;family=Sora:wght@600;700;800&amp;display=swap" rel="stylesheet">
<?php $css = @file_get_contents(__DIR__ . '/lp-glass.css'); if ($css): ?><style><?= $css ?></style><?php else: ?><link rel="stylesheet" href="/lp/lp-glass.css"><?php endif; ?><script type="application/ld+json"><?= json_encode($courseSchema, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?></script><script type="application/ld+json"><?= json_encode($faqSchema, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?></script>
<script>window.dataLayer=window.dataLayer||[];window.dataLayer.push({'gtm.start':Date.now(),event:'gtm.js',landing_program:'<?= $e($slug) ?>'});(function(w,d,s,l,i){var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)})(window,document,'script','dataLayer','<?= $GTM ?>');</script></head><body>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?= $GTM ?>" height="0" width="0" style="display:none;visibility:hidden" title="Google Tag Manager"></iframe></noscript>
<header class="topbar"><div class="shell topbar-inner"><a class="brand" href="https://wahanatotalita.com/" aria-label="Wahana Totalita Konsultan"><span class="brand-mark">WT</span><span>Wahana Totalita<small>Safety training &amp; consulting</small></span></a><a class="top-wa wa-track" data-position="header" href="<?= $e($waUrl('Konsultasi cepat')) ?>" target="_blank" rel="noopener">Konsultasi WA</a></div></header><main>
<section class="hero"><div class="shell hero-grid"><div class="hero-copy"><span class="eyebrow"><?= $e($LP['badge'] ?? 'Pelatihan & Sertifikasi K3') ?></span><h1><?= $LP['h1'] ?? $e($program) ?></h1><p class="hero-lead"><?= $e($LP['lead'] ?? '') ?></p><div class="quick-facts"><?php foreach(array_slice($summary,0,4) as $row): ?><div><span><?= $e($row[0]) ?></span><strong><?= strip_tags((string)$row[1], '<s><br>') ?></strong></div><?php endforeach; ?></div><a class="wa-button wa-track" data-position="hero" href="<?= $e($waUrl($heroCta)) ?>" target="_blank" rel="noopener"><?= $WASVG ?><span><?= $e($heroCta) ?><small>Langsung melalui WhatsApp</small></span></a><p class="micro-proof">Gratis konsultasi awal · Tanpa kewajiban mendaftar</p></div><div class="hero-media"><img src="<?= $e($imageUrl($heroImage)) ?>" alt="<?= $e($heroAlt) ?>" width="1600" height="1067" fetchpriority="high" decoding="async"><div class="media-caption"><b>Dokumentasi kegiatan</b><span><?= $e($gallery[0][1] ?? $heroAlt) ?></span></div><div class="price-chip"><span>Investasi</span><strong><?= $e($price) ?></strong><small><?= $e($schedule ?: ($LP['urg'] ?? 'Tanyakan batch terdekat')) ?></small></div></div></div></section>
<section class="trust"><div class="shell"><p class="trust-title">Sebagian perusahaan dan institusi dalam dokumentasi klien kami</p><div class="logo-row"><?php foreach($clientLogos as $logo): ?><img src="<?= $e($imageUrl($logo[0])) ?>" alt="<?= $e($logo[1]) ?>" loading="lazy" decoding="async"><?php endforeach; ?></div></div></section>
<section class="confidence-strip" aria-label="Komitmen informasi sebelum pendaftaran"><div class="shell confidence-grid"><div><b>01</b><span><strong>Cek kelayakan dahulu</strong>Persyaratan awal diperiksa sebelum Anda memilih program.</span></div><div><b>02</b><span><strong>Rincian tertulis</strong>Jadwal, metode, fasilitas, dan biaya dikonfirmasi sebelum pembayaran.</span></div><div><b>03</b><span><strong>Hasil mengikuti asesmen</strong>Sertifikat tidak dijanjikan; penerbitan mengikuti hasil dan ketentuan lembaga terkait.</span></div></div></section>
<section class="section fit-section"><div class="shell two-col"><div><span class="section-kicker">Cocok untuk siapa?</span><h2><?= $e($LP['fit_h2'] ?? 'Pastikan programnya sesuai sebelum mendaftar') ?></h2><p class="section-intro"><?= $e($LP['fit_intro'] ?? 'Program yang tepat bergantung pada posisi, pendidikan, pengalaman, dan tujuan sertifikasi Anda.') ?></p><ul class="check-list"><?php foreach($audience as $item): ?><li><?= $e($item) ?></li><?php endforeach; ?></ul></div><aside class="check-card"><span class="card-label">Cek awal gratis</span><h3>Belum yakin Anda memenuhi syarat?</h3><p>Kirim pendidikan terakhir dan pengalaman kerja. Tim akan membantu memeriksa jalur yang paling sesuai.</p><a class="text-cta wa-track" data-position="eligibility" href="<?= $e($waUrl('Periksa kelayakan peserta')) ?>" target="_blank" rel="noopener">Kirim profil untuk dicek →</a></aside></div></section>
<section class="section outcome-section"><div class="shell"><span class="section-kicker">Yang Anda dapatkan</span><div class="section-heading"><h2>Bukan hanya ikut kelas</h2><p>Setiap tahap dibuat jelas agar Anda memahami program, proses, dan dokumen sebelum mengambil keputusan.</p></div><div class="outcome-grid"><?php foreach($outcomes as $i=>$item): ?><article><b>0<?= $i+1 ?></b><h3><?= $e($item[0]) ?></h3><p><?= $e($item[1]) ?></p></article><?php endforeach; ?></div></div></section>
<section class="topics-section"><div class="shell topics-wrap"><div><span class="section-kicker">Gambaran materi</span><h2><?= $e($LP['topics_h2'] ?? 'Apa yang akan dipelajari?') ?></h2><p><?= $e($LP['topics_intro'] ?? 'Materi difokuskan pada pengetahuan dan penerapan yang relevan dengan program.') ?></p></div><ol class="topic-list"><?php foreach($topics as $i=>$topic): ?><li><span><?= str_pad((string)($i+1), 2, '0', STR_PAD_LEFT) ?></span><?= $e($topic) ?></li><?php endforeach; ?></ol></div></section>
<section class="section evidence-section"><div class="shell evidence-grid"><figure><img src="<?= $e($imageUrl($gallery[1][0] ?? $heroImage)) ?>" alt="<?= $e($gallery[1][1] ?? $heroAlt) ?>" width="1600" height="1067" loading="lazy" decoding="async"><figcaption>Dokumentasi kegiatan aktual · <?= $e($gallery[1][1] ?? 'Dokumentasi pelatihan') ?></figcaption></figure><div><span class="section-kicker">Persyaratan awal</span><h2>Siapkan dokumen tanpa menebak</h2><p class="section-intro">Daftar berikut adalah pemeriksaan awal. Ketentuan akhir mengikuti skema dan lembaga penerbit.</p><ul class="document-list"><?php foreach($requirements as $item): ?><li><?= $e($item) ?></li><?php endforeach; ?></ul><a class="secondary-button wa-track" data-position="documents" href="<?= $e($waUrl('Minta checklist dokumen')) ?>" target="_blank" rel="noopener">Minta Checklist via WhatsApp</a></div></div></section>
<section class="section detail-section" id="detail"><div class="shell offer-grid"><div><span class="section-kicker">Detail program</span><h2><?= $e($program) ?></h2><div class="summary-table"><?php foreach($summary as $row): ?><div><span><?= $e($row[0]) ?></span><strong><?= strip_tags((string)$row[1], '<s><br>') ?></strong></div><?php endforeach; ?></div><div class="disclosure"><strong>Penting sebelum mendaftar</strong><p>Jadwal, metode, fasilitas, persyaratan, lembaga penerbit, dan komponen biaya akan dikonfirmasi secara tertulis. Penerbitan sertifikat mengikuti kelulusan asesmen serta ketentuan lembaga terkait.</p></div></div><aside class="offer-card"><span class="offer-label">Investasi per peserta</span><?php if($oldPrice): ?><s><?= $e($oldPrice) ?></s><?php endif; ?><strong class="offer-price"><?= $e($price) ?></strong><small><?= $e($LP['price_note'] ?? 'Konfirmasi rincian sebelum pembayaran') ?></small><ul><?php foreach($includes as $item): ?><li><?= $e(strip_tags($item)) ?></li><?php endforeach; ?></ul><a class="wa-button block wa-track" data-position="price" href="<?= $e($waUrl($priceCta)) ?>" target="_blank" rel="noopener"><?= $WASVG ?><span><?= $e($priceCta) ?><small>Jadwal &amp; fasilitas lengkap</small></span></a><p class="offer-reassurance">Tidak ada pembayaran melalui halaman ini. Minta rincian tertulis terlebih dahulu.</p></aside></div></section>
<section class="section process-section"><div class="shell"><span class="section-kicker">Alur sederhana</span><h2>Dari pertanyaan sampai pelaksanaan</h2><ol class="process"><li><b>1</b><div><h3>Kirim profil</h3><p>Sampaikan program, pendidikan, dan pengalaman singkat.</p></div></li><li><b>2</b><div><h3>Cek persyaratan</h3><p>Tim membantu memeriksa skema dan dokumen awal.</p></div></li><li><b>3</b><div><h3>Konfirmasi tertulis</h3><p>Terima rincian batch, metode, biaya, dan fasilitas.</p></div></li><li><b>4</b><div><h3>Daftar dan ikuti proses</h3><p>Selesaikan administrasi lalu ikuti pelatihan dan tahapan lanjutan.</p></div></li></ol></div></section>
<section class="section faq-section"><div class="shell faq-grid"><div><span class="section-kicker">Pertanyaan sebelum daftar</span><h2>Jawaban yang perlu Anda tahu</h2><p>Jika situasi Anda berbeda, tim dapat membantu menjawabnya melalui WhatsApp.</p></div><div class="faq-list"><?php foreach($faqs as $i=>$faq): ?><details<?= $i===0?' open':'' ?>><summary><?= $e($faq[0]) ?></summary><p><?= $e($faq[1]) ?></p></details><?php endforeach; ?></div></div></section>
<section class="final-section"><div class="shell final-inner"><div><span class="section-kicker light">Langkah berikutnya</span><h2><?= $e($LP['final_h2'] ?? 'Periksa persyaratan Anda sekarang') ?></h2><p><?= $e($LP['final_p'] ?? 'Kirim profil singkat. Tim akan membantu mengecek program, batch, dan persyaratan sebelum Anda memutuskan.') ?></p></div><a class="wa-button wa-track" data-position="final" href="<?= $e($waUrl('Mulai konsultasi')) ?>" target="_blank" rel="noopener"><?= $WASVG ?><span>Mulai Konsultasi<small>Respons melalui WhatsApp</small></span></a></div></section></main>
<footer><div class="shell footer-grid"><div class="footer-about"><div class="footer-brand"><span class="brand-mark">WT</span><strong>Wahana Totalita Konsultan</strong></div><p>Pelatihan dan konsultasi keselamatan kerja untuk individu dan perusahaan.</p></div><div class="footer-group"><b>Kontak halaman ini</b><a href="tel:+6287759151278">0877-5915-1278</a><a href="mailto:info@wahanatotalita.com">info@wahanatotalita.com</a><span>Yogyakarta, Indonesia</span></div><nav class="footer-group" aria-label="Informasi footer"><b>Informasi</b><a href="/kebijakan-privasi">Kebijakan Privasi</a><a href="/jadwal/">Jadwal Pelatihan</a></nav></div><div class="shell copyright"><span>&copy; <?= $year ?> Wahana Totalita Konsultan</span><span>Informasi program dikonfirmasi sebelum pendaftaran.</span></div></footer><div class="sticky-cta"><div><span>Cek program</span><strong><?= $e($program) ?></strong></div><a href="<?= $e($waUrl($stickyCta)) ?>" class="sticky-button wa-track" data-position="sticky" target="_blank" rel="noopener" aria-label="<?= $e($stickyCta) ?> untuk <?= $e($program) ?>"><?= $WASVG ?> <?= $e($stickyCta) ?></a></div><script>(function(){var keys=['utm_source','utm_medium','utm_campaign','utm_content','utm_term','gclid','fbclid'];var query=new URLSearchParams(location.search),saved={};keys.forEach(function(k){var v=query.get(k);if(v){try{sessionStorage.setItem('lp_'+k,v)}catch(e){}}try{v=v||sessionStorage.getItem('lp_'+k)}catch(e){}if(v)saved[k]=v});var source=Object.keys(saved).map(function(k){return k+'='+saved[k]}).join(' | ');document.querySelectorAll('.wa-track').forEach(function(a){if(source){var u=new URL(a.href),message=u.searchParams.get('text')||'';u.searchParams.set('text',message+'\nSumber: '+source);a.href=u.toString()}a.addEventListener('click',function(){var payload={event:'whatsapp_click',program:'<?= $e($slug) ?>',position:this.dataset.position||'unknown',cta:this.textContent.trim(),page_path:location.pathname};Object.keys(saved).forEach(function(k){payload[k]=saved[k]});window.dataLayer=window.dataLayer||[];window.dataLayer.push(payload)})});window.dataLayer.push(Object.assign({event:'landing_page_view',program:'<?= $e($slug) ?>',page_path:location.pathname},saved))})();</script></body></html>
