<?php
/** Inline icon paths (24x24 viewBox), used via icon($name) in templates/includes. Generated by build/gen_svg.php. */
return [
  'shield-check' => '<path d="M12 3 L19 6 V11 C19 16 15.5 19.5 12 21 C8.5 19.5 5 16 5 11 V6 Z"/><path d="M9 11.5 L11 13.5 L15 9"/>',
  'file-text' => '<path d="M7 3 H14 L18 7 V21 H7 Z"/><path d="M14 3 V7 H18"/><path d="M9.5 12 H15.5 M9.5 15.5 H15.5 M9.5 18 H13"/>',
  'award' => '<circle cx="12" cy="8" r="5"/><path d="M9 12.5 L7.5 21 L12 18.5 L16.5 21 L15 12.5"/>',
  'clipboard-check' => '<rect x="6" y="4" width="12" height="17" rx="2"/><path d="M9 4 V3.3 a1 1 0 0 1 1 -1 h4 a1 1 0 0 1 1 1 V4"/><path d="M9 12.5 L11 14.5 L15.5 9.5"/>',
  'factory' => '<path d="M4 21 V10 L10 13 V10 L16 13 V7 L20 10 V21 Z"/><path d="M4 21 H20"/><path d="M8 21 v-4 M13 21 v-4"/>',
  'bar-chart' => '<rect x="4" y="13" width="3.4" height="8"/><rect x="10.3" y="8" width="3.4" height="13"/><rect x="16.6" y="4" width="3.4" height="17"/>',
  'search' => '<circle cx="10.5" cy="10.5" r="6.5"/><path d="M20 20 L15.3 15.3"/>',
  'help-circle' => '<circle cx="12" cy="12" r="9"/><path d="M9.3 9.3 a2.7 2.7 0 1 1 3.9 2.4 c-1.1 .6 -1.2 1.3 -1.2 2.3"/><circle cx="12" cy="17.1" r=".65" fill="currentColor" stroke="none"/>',
  'book-open' => '<path d="M12 6 C10 4.5 6.5 4 4 4.5 V19 C6.5 18.5 10 19 12 20.5 C14 19 17.5 18.5 20 19 V4.5 C17.5 4 14 4.5 12 6 Z"/><path d="M12 6 V20.5"/>',
  'graduation-cap' => '<path d="M2 9 L12 4 L22 9 L12 14 Z"/><path d="M6 11.3 V17 C6 18.5 8.5 19.5 12 19.5 C15.5 19.5 18 18.5 18 17 V11.3"/><path d="M22 9 V15"/>',
  'edit' => '<path d="M4 20 L4 16.3 L15.4 4.9 a2.1 2.1 0 0 1 3 3 L6.6 20 Z"/><path d="M13 6.9 L17.1 11"/>',
  'check' => '<path d="M4 12.5 L9 17.5 L20 6"/>',
  'info' => '<circle cx="12" cy="12" r="9"/><path d="M12 11 V16.5"/><circle cx="12" cy="7.7" r=".7" fill="currentColor" stroke="none"/>',
  'warning' => '<path d="M12 3.3 L22 20.5 H2 Z"/><path d="M12 9.3 V14.3"/><circle cx="12" cy="17.4" r=".7" fill="currentColor" stroke="none"/>',
  'danger' => '<circle cx="12" cy="12" r="9"/><path d="M9 9 L15 15 M15 9 L9 15"/>',
  'chevron-right' => '<path d="M9 5 L16 12 L9 19"/>',
  'arrow-right' => '<path d="M4 12 H20 M14 6 L20 12 L14 18"/>',
  'whatsapp' => '<path d="M12 2C6.5 2 2 6.5 2 12c0 1.9.5 3.7 1.5 5.3L2 22l4.9-1.4C8.4 21.5 10.1 22 12 22c5.5 0 10-4.5 10-10S17.5 2 12 2z"/>',
  'clock' => '<circle cx="12" cy="12" r="9"/><path d="M12 7 V12 L15.5 14.5"/>',
];
