-- /k3 engine — schema for the u566907099_tags database.
-- This DB is INDEPENDENT of u566907099_wahana_db. Program data is mirrored
-- (read-only) into programs_cache by database/sync_run.php; the tags DB user
-- never touches the main DB directly at request time.

-- Read-only mirror of the main site's `trainings` table (source of truth).
-- Populated only by sync_run.php — never hand-edited.
CREATE TABLE IF NOT EXISTS programs_cache (
  id INT PRIMARY KEY,                 -- = trainings.id
  slug VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) NULL,
  duration_days TINYINT NULL,
  mode ENUM('online','offline','both') NULL,
  certification VARCHAR(190) NULL,
  category_id INT NULL,
  description TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  external_url VARCHAR(500) NOT NULL,  -- link to the real sales page on the main site
  synced_at TIMESTAMP NULL,
  INDEX idx_active (is_active),
  INDEX idx_cert (certification),
  FULLTEXT idx_ft (name, description, certification)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- The long-tail surface. One row = one keyword phrase we can SERVE on demand.
-- Generated by database/keywords_build.php from programs_cache x modifiers x cities.
-- These are NOT one-URL-per-row. They power: (a) on-demand matching for
-- /k3?q= or /k3/{slug}, (b) an internal topical index on the /k3 hub.
-- is_promoted stays 0 (served but the hub stays the only indexed URL) until you
-- manually decide a specific phrase deserves its own indexed treatment later.
CREATE TABLE IF NOT EXISTS keywords (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phrase VARCHAR(255) NOT NULL,        -- human phrase, e.g. "biaya pelatihan ahli k3 umum"
  norm_slug VARCHAR(255) NOT NULL,     -- normalized, e.g. "biaya-pelatihan-ahli-k3-umum"
  program_id INT NULL,                 -- best-matching program (nullable)
  modifier VARCHAR(60) NULL,           -- biaya | jadwal | syarat | online | kota | ...
  city VARCHAR(80) NULL,
  is_promoted TINYINT(1) NOT NULL DEFAULT 0,
  hits INT NOT NULL DEFAULT 0,         -- optional demand counter
  UNIQUE KEY uq_norm (norm_slug),
  INDEX idx_program (program_id),
  INDEX idx_modifier (modifier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- FAQ blocks shown on the hub / on-demand pages. Optionally scoped to a program.
CREATE TABLE IF NOT EXISTS faqs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  program_id INT NULL,                 -- NULL = generic, shown everywhere
  question VARCHAR(500) NOT NULL,
  answer TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  INDEX idx_program (program_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
